# Generated by Django 4.2.7 on 2023-11-27 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_session_date_alter_attendance_status_delete_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='session_number',
            field=models.IntegerField(default=1),
        ),
    ]
