# Generated by Django 4.2.3 on 2023-11-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snappy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='professors',
        ),
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(to='snappy.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(to='snappy.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='None', max_length=255),
        ),
    ]
